nama = input("Nama                     :")
nim  = input("NIM                      :")
kelas = input("Kelas Paralel            :")
ttl = input("Tempat/Tanggal Lahir     :")
alamat = input("Alamat                   :")
hobi = input("Hobby                    :")
no = input("No. HP                   :")

print("")

print("Nama                     : " + nama)
print("NIM                      : " + nim)
print("Kelas Paralel            : " + kelas)
print("Tempat/Tanggal Lahir     : " + ttl)
print("Alamat                   : " + alamat)
print("Hobby                    : " + hobi)
print("No. HP                   : " + no)